USE [master]
GO
/****** Object:  Database [HollardTestDb]    Script Date: 15-10-2024 21:37:20 ******/
CREATE DATABASE [HollardTestDb]

GO
ALTER DATABASE [HollardTestDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HollardTestDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HollardTestDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HollardTestDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HollardTestDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HollardTestDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HollardTestDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [HollardTestDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [HollardTestDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HollardTestDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HollardTestDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HollardTestDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HollardTestDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HollardTestDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HollardTestDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HollardTestDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HollardTestDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HollardTestDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HollardTestDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HollardTestDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HollardTestDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HollardTestDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HollardTestDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HollardTestDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HollardTestDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HollardTestDb] SET  MULTI_USER 
GO
ALTER DATABASE [HollardTestDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HollardTestDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HollardTestDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HollardTestDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HollardTestDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HollardTestDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HollardTestDb] SET QUERY_STORE = OFF
GO
USE [HollardTestDb]
GO
/****** Object:  Schema [insurance]    Script Date: 15-10-2024 21:37:20 ******/
CREATE SCHEMA [insurance]
GO
/****** Object:  Table [dbo].[CoverDetails]    Script Date: 15-10-2024 21:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CoverDetails](
	[CoverDetailId] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [uniqueidentifier] NULL,
	[CoverStartDate] [date] NULL,
	[CoverEndDate] [date] NULL,
	[PremiumPayoutTerm] [nchar](10) NULL,
	[BranchCode] [nvarchar](10) NULL,
	[Quotenumber] [nvarchar](200) NULL,
	[QuoteDate] [date] NULL,
 CONSTRAINT [PK_dbo_CoverDetails_Id] PRIMARY KEY CLUSTERED 
(
	[CoverDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 15-10-2024 21:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [uniqueidentifier] NOT NULL,
	[Title] [nchar](10) NULL,
	[Email] [varchar](255) NOT NULL,
	[Name] [varchar](200) NULL,
	[Surname] [varchar](200) NULL,
	[Password] [varchar](255) NULL,
	[Phone] [varchar](20) NULL,
	[Address1] [nvarchar](200) NULL,
	[Address2] [nvarchar](200) NULL,
 CONSTRAINT [PK_dbo_Customers_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RiskDetails]    Script Date: 15-10-2024 21:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RiskDetails](
	[RiskDetailId] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [uniqueidentifier] NULL,
	[CoverDetailId] [int] NULL,
	[MakeId] [int] NULL,
	[ModelId] [int] NULL,
	[SumInsured] [bigint] NULL,
	[VehicleCost] [bigint] NULL,
	[RateApplied] [int] NULL,
	[Premium] [int] NULL,
	[YearOfManufacture] [int] NULL,
 CONSTRAINT [PK_dbo_RiskDetails_Id] PRIMARY KEY CLUSTERED 
(
	[RiskDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [HollardTestDb] SET  READ_WRITE 
GO
